pipeline {
    agent any
    
    environment {
        DOCKER_USERNAME = credentials('docker-hub-username')
        DOCKER_PASSWORD = credentials('docker-hub-password')
	PROJECT_DIR = "applications/devbox-spring-demo/"
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }
        
        stage('Log in to Docker Hub') {
            steps {
                script {
                    sh "echo \$DOCKER_PASSWORD | docker login -u \$DOCKER_USERNAME --password-stdin"
                }
            }
        }
        
        stage('Build and Push Docker Image') {
            steps {
                script {
		    dir("$PROJECT_DIR") {
                    sh "docker build -t \$DOCKER_USERNAME/java-maven-app:latest ."
                    sh "docker push \$DOCKER_USERNAME/java-maven-app:latest"

                }
            }
        }
   }
        
 }

}

